/**
 * PROVEEDORES — Directorio de negocios locales
 * En v3: se carga desde Firestore (colección /negocios)
 */
export const PROVEEDORES = [
  {
    id:'p1', tipo:'local', av:'EM', bg:'#E1F5EE', co:'#0F6E56',
    nm:'El Mirador Restaurante', cat:'Restaurante · Gastronomía', web:'https://elmirador.micanton.cr',
    catalogType:'menu',
    tags:'restaurante comida casado almuerzo comer gastronomía',
    filtro:'negocios', zona:'Centro · Alajuela',
    dir:'200m norte del Parque Central, Alajuela',
    waze:'https://waze.com/ul?q=El+Mirador+Alajuela',
    maps:'https://maps.google.com/?q=El+Mirador+Alajuela',
    tel:'8888-0001', wa:'50688880001',
    rt:4.9, rv:124, abierto:true, horario:'Lun–Sáb 10am–9pm · Dom cerrado',
    precio:'₡3.500–₡6.000', pago:'SINPE · tarjeta · efectivo',
    wifi:true, acc:true,
    desc:'El mejor casado del cantón. Ingredientes frescos del día, ambiente familiar y porciones generosas. 15 años sirviéndole a Alajuela.',
    servicios:['Casados · Almuerzo','Sopa del día','Pedidos para llevar','Reservaciones'],
    fotos:6, reseñas:124, verificado:true, featured:true,
    catalogo:[
      {nm:'Casado con pollo',pr:'₡3.500',cat:'Casados',foto:true,popular:true},
      {nm:'Casado con carne',pr:'₡4.200',cat:'Casados',foto:true,popular:false},
      {nm:'Olla de carne',pr:'₡5.800',cat:'Casados',foto:true,popular:true},
      {nm:'Sopa negra',pr:'₡2.800',cat:'Sopas',foto:false,popular:false},
      {nm:'Refresco natural',pr:'₡800',cat:'Bebidas',foto:false,popular:false},
    ],
  },
  {
    id:'p2', tipo:'independiente', av:'CR', bg:'#FAEEDA', co:'#854F0B',
    nm:'Carlos Rodríguez · Fontanero', cat:'Fontanería · Servicios del hogar',
    tags:'fontanero plomero tubería agua servicio domicilio reparación',
    filtro:'servicios', zona:'Cantón central · Alajuela',
    dir:'Atiende a domicilio en Alajuela, San Ramón y Grecia',
    waze:null, maps:null,
    tel:'8888-0010', wa:'50688880010',
    rt:4.9, rv:47, abierto:true, horario:'Lun–Vie 7am–5pm · Sáb 8am–1pm',
    precio:'Desde ₡15.000/visita', pago:'SINPE · efectivo',
    wifi:false, acc:false,
    desc:'Fontanero certificado con 12 años de experiencia. Especialista en tuberías PVC y cobre. Trabajo garantizado por escrito.',
    servicios:['Reparación de tuberías','Instalación de grifos','Corrección de filtraciones','Instalación de sanitarios'],
    fotos:4, reseñas:47, verificado:true, featured:false,
    catalogo:[
      {nm:'Reparación tuberías',pr:'Desde ₡15.000',cat:'Servicio',foto:false,popular:true},
      {nm:'Instalación grifos',pr:'Desde ₡8.000',cat:'Servicio',foto:false,popular:false},
      {nm:'Corrección filtraciones',pr:'Desde ₡20.000',cat:'Servicio',foto:false,popular:false},
      {nm:'Instalación sanitarios',pr:'Desde ₡25.000',cat:'Servicio',foto:false,popular:false},
    ],
  },
  {
    id:'p3', tipo:'empresa', av:'PV', bg:'#E6F1FB', co:'#185FA5',
    nm:'Plomería Vargas & Hijos', cat:'Fontanería industrial · Empresa',
    tags:'fontanero plomero empresa tubería agua industrial residencial comercial',
    filtro:'servicios', zona:'Toda la provincia · Alajuela',
    dir:'Bo. Guadalupe, Alajuela. Atiende toda la provincia.',
    waze:'https://waze.com/ul?q=Bo+Guadalupe+Alajuela',
    maps:'https://maps.google.com/?q=Bo+Guadalupe+Alajuela',
    tel:'2441-0023', wa:'50624410023',
    rt:4.8, rv:186, abierto:true, horario:'Lun–Vie 7am–6pm · Sáb 8am–2pm',
    precio:'Cotización gratuita', pago:'SINPE · tarjeta · cheque · factura',
    wifi:false, acc:true,
    desc:'Empresa familiar con 18 años en el mercado. 5 técnicos certificados. Atendemos residencias, condominios y empresas. Factura electrónica.',
    servicios:['Proyectos residenciales','Sistemas comerciales','Mantenimiento preventivo','Emergencias 24/7'],
    fotos:8, reseñas:186, verificado:true, featured:true,
    equipo:5,
    catalogo:[
      {nm:'Diagnóstico y presupuesto',pr:'Gratis',cat:'Servicio',foto:false,popular:true},
      {nm:'Proyecto residencial completo',pr:'Cotización',cat:'Proyecto',foto:true,popular:false},
      {nm:'Mantenimiento preventivo',pr:'Desde ₡45.000',cat:'Servicio',foto:false,popular:false},
      {nm:'Emergencias 24/7',pr:'Desde ₡25.000',cat:'Urgente',foto:false,popular:true},
    ],
  },
  {
    id:'p4', tipo:'agencia', av:'AD', bg:'#EEEDFE', co:'#534AB7',
    nm:'Agencia Diseño CR', cat:'Diseño · Marketing digital',
    tags:'diseño gráfico marketing redes sociales posts reels instagram agencia creativo',
    filtro:'diseño', zona:'Todo el país · Remoto',
    dir:'100% remoto. Reuniones virtuales o en oficina Alajuela.',
    waze:null, maps:null,
    tel:'8888-2020', wa:'50688882020',
    rt:4.7, rv:38, abierto:true, horario:'Lun–Vie 8am–6pm',
    precio:'Desde ₡25.000/pieza', pago:'SINPE · transferencia · tarjeta',
    wifi:false, acc:false,
    desc:'Agencia creativa con 4 diseñadores. Especializados en branding y contenido para redes sociales. +200 clientes en Costa Rica.',
    servicios:['Posts y stories Instagram','Reels y TikTok','Identidad visual completa','Gestión mensual RRSS'],
    fotos:12, reseñas:38, verificado:true, featured:false,
    equipo:4,
    catalogo:[
      {nm:'Post feed Instagram',pr:'₡25.000',cat:'Diseño',foto:true,popular:true},
      {nm:'Carrusel 5 slides',pr:'₡45.000',cat:'Diseño',foto:true,popular:true},
      {nm:'Reel · 30 segundos',pr:'₡80.000',cat:'Video',foto:true,popular:false},
      {nm:'Pack mensual RRSS',pr:'₡180.000/mes',cat:'Plan',foto:false,popular:true},
    ],
  },
  {
    id:'p5', tipo:'local', av:'FS', bg:'#EAF3DE', co:'#3B6D11',
    nm:'Farmacia San Juan',    wa:'50688880002', tel:'8888-0002', cat:'Farmacia · Salud',
    tags:'farmacia medicina medicamento pastilla vitamina salud',
    filtro:'negocios', zona:'Centro · Alajuela',
    dir:'Av. Central, 50m sur del Parque Central, Alajuela',
    waze:'https://waze.com/ul?q=Farmacia+San+Juan+Alajuela',
    maps:'https://maps.google.com/?q=Farmacia+San+Juan+Alajuela',
    tel:'2441-0050', wa:'50624410050',
    rt:4.7, rv:89, abierto:true, horario:'Lun–Sáb 7am–9pm · Dom 8am–6pm',
    precio:'Precio de lista', pago:'SINPE · tarjeta · efectivo · CCSS',
    wifi:false, acc:true,
    desc:'Farmacia de barrio con 20 años al servicio del cantón. Medicamentos, vitaminas, artículos de salud y asesoría farmacéutica.',
    servicios:['Medicamentos con receta','Vitaminas y suplementos','Artículos de cuidado personal','Toma de presión arterial gratis'],
    fotos:3, reseñas:89, verificado:true, featured:false,
    catalogo:[
      {nm:'Vitamina C 1000mg x30',pr:'₡4.200',cat:'Vitaminas',foto:false,popular:true},
      {nm:'Multivitamínico adulto',pr:'₡8.500',cat:'Vitaminas',foto:false,popular:true},
      {nm:'Ibuprofeno 400mg x10',pr:'₡1.800',cat:'Analgésico',foto:false,popular:false},
    ],
  },
  {
    id:'p6', tipo:'independiente', av:'LM', bg:'#E1F5EE', co:'#085041',
    nm:'Laura Méndez · Limpieza del hogar', cat:'Limpieza · Servicios del hogar',
    tags:'limpieza hogar doméstica plancha orden aseo servicio',
    filtro:'servicios', zona:'Alajuela · San Ramón · Grecia',
    dir:'Atiende a domicilio. Zona: Alajuela, San Ramón, Grecia.',
    waze:null, maps:null,
    tel:'8888-0020', wa:'50688880020',
    rt:4.8, rv:89, abierto:true, horario:'Lun–Sáb 7am–5pm',
    precio:'Desde ₡35.000/día', pago:'SINPE · efectivo',
    wifi:false, acc:false,
    desc:'Servicio de limpieza, plancha y orden del hogar. Referencias disponibles. Discreta y puntual. 8 años de experiencia.',
    servicios:['Limpieza general','Limpieza profunda','Plancha y orden','Contrato mensual'],
    fotos:4, reseñas:89, verificado:true, featured:false,
    catalogo:[
      {nm:'Limpieza general',pr:'₡35.000/día',cat:'Servicio',foto:false,popular:true},
      {nm:'Limpieza profunda',pr:'₡50.000',cat:'Servicio',foto:false,popular:false},
      {nm:'Plancha y orden',pr:'₡20.000',cat:'Servicio',foto:false,popular:false},
      {nm:'Contrato mensual',pr:'Desde ₡180.000',cat:'Plan',foto:false,popular:true},
    ],
  },
  {
    id:'p7', tipo:'independiente', av:'AM', bg:'#FCEBEB', co:'#A32D2D',
    nm:'Alejandro Mora · Electricista', cat:'Electricidad · Servicios del hogar',
    tags:'electricista eléctrico instalación tablero luminaria avería luz',
    filtro:'servicios', zona:'Cantón central · Alajuela',
    dir:'Atiende a domicilio en Alajuela centro.',
    waze:null, maps:null,
    tel:'8888-0030', wa:'50688880030',
    rt:4.6, rv:28, abierto:false, horario:'Lun–Vie 7am–5pm (hoy no disponible)',
    precio:'Desde ₡18.000/visita', pago:'SINPE · efectivo',
    wifi:false, acc:false,
    desc:'Electricista certificado CFIA. Instalaciones residenciales y comerciales. Trabajo garantizado.',
    servicios:['Revisión eléctrica','Instalación de tablero','Corrección de averías','Luminarias LED'],
    fotos:3, reseñas:28, verificado:true, featured:false,
    catalogo:[
      {nm:'Revisión eléctrica',pr:'Desde ₡18.000',cat:'Servicio',foto:false,popular:true},
      {nm:'Instalación tablero',pr:'Cotización',cat:'Proyecto',foto:false,popular:false},
      {nm:'Luminarias LED',pr:'Desde ₡8.000',cat:'Servicio',foto:false,popular:false},
    ],
  },
  {
    id:'p8', tipo:'local', av:'CD', bg:'#FCEBEB', co:'#A32D2D',
    nm:'Clínica Dental Dr. Soto', cat:'Salud · Odontología',
    tags:'dental dentista diente revisión limpieza salud clínica',
    filtro:'negocios', zona:'B. San José · Alajuela',
    dir:'Bo. San José, de la Iglesia 200m este, Alajuela',
    waze:'https://waze.com/ul?q=Clinica+Dental+Soto+Alajuela',
    maps:'https://maps.google.com/?q=Clinica+Dental+Soto+Alajuela',
    tel:'2441-0080', wa:'50624410080',
    rt:4.9, rv:201, abierto:true, horario:'Lun–Vie 8am–6pm · Sáb 8am–12pm',
    precio:'Desde ₡15.000', pago:'SINPE · tarjeta · crédito · INS',
    wifi:true, acc:true,
    desc:'Clínica dental familiar con 15 años. Dr. Marco Soto y equipo. Limpiezas, ortodoncia, implantes y emergencias.',
    servicios:['Limpieza dental','Revisión y diagnóstico','Ortodoncia','Implantes dentales'],
    fotos:5, reseñas:201, verificado:true, featured:true,
    catalogo:[
      {nm:'Limpieza dental + revisión',pr:'₡25.000',cat:'Preventivo',foto:false,popular:true},
      {nm:'Radiografía panorámica',pr:'₡15.000',cat:'Diagnóstico',foto:false,popular:false},
      {nm:'Extracción simple',pr:'Desde ₡18.000',cat:'Cirugía',foto:false,popular:false},
      {nm:'Consulta de emergencia',pr:'₡20.000',cat:'Urgente',foto:false,popular:false},
    ],
  },,
  {id:2,in:'AM',bg:'#EEEDFE',co:'#534AB7',nm:'Ana Monge',tel:'8888-1002',wa:'50688881002',
   of:'Diseñadora gráfica',rt:4.8,rv:31,zona:'Cantón central',disp:true,prem:false,nw:true,
   desc:'Diseñadora con 8 años de experiencia en branding, redes sociales y material impreso.',
   catalogType:'servicios',
   items:[
     {id:'s1',nm:'Logo profesional',desc:'Incluye 3 propuestas, 2 revisiones, archivos en AI y PNG.',pr:'₡45.000',prNum:45000,cat:'Branding',sub:'Identidad visual',img:null,activo:true,popular:true},
     {id:'s2',nm:'Diseño de post RRSS',desc:'Pack de 5 publicaciones optimizadas para Instagram y Facebook.',pr:'₡18.000',prNum:18000,cat:'Redes Sociales',sub:'Posts',img:null,activo:true,popular:true},
     {id:'s3',nm:'Flyer digital A4',desc:'Diseño para eventos, productos o servicios. 1 revisión.',pr:'₡8.500',prNum:8500,cat:'Material impreso',sub:'Flyers',img:null,activo:true,popular:false},
     {id:'s4',nm:'Tarjeta de presentación',desc:'Diseño 2 caras. Incluye archivo listo para imprenta.',pr:'₡6.000',prNum:6000,cat:'Material impreso',sub:'Tarjetas',img:null,activo:false,popular:false},
   ],
   svcs:[{n:'Logo',p:'₡45.000'},{n:'Posts RRSS',p:'₡18.000'},{n:'Flyer',p:'₡8.500'}]
  },
  {id:3,in:'LV',bg:'#FFF0D6',co:'#C07000',nm:'Luis Vargas',tel:'8888-1003',wa:'50688881003',
   of:'Electricista certificado',rt:5.0,rv:22,zona:'San Ramón',disp:true,prem:false,nw:false,
   desc:'Instalaciones eléctricas residenciales y comerciales. Certificado ICE.',
   catalogType:'servicios',
   items:[
     {id:'e1',nm:'Revisión panel eléctrico',desc:'Inspección completa, reporte escrito y cotización.',pr:'₡15.000',prNum:15000,cat:'Inspecciones',sub:'Residencial',img:null,activo:true,popular:true},
     {id:'e2',nm:'Instalación toma corriente',desc:'Material e instalación incluidos. Por punto.',pr:'₡12.000',prNum:12000,cat:'Instalaciones',sub:'Residencial',img:null,activo:true,popular:false},
     {id:'e3',nm:'Cambio de breaker',desc:'Diagnóstico, pieza y mano de obra.',pr:'₡20.000',prNum:20000,cat:'Mantenimiento',sub:'Panel',img:null,activo:true,popular:false},
     {id:'e4',nm:'Instalación luminarias LED',desc:'Por punto. Material no incluido.',pr:'₡8.000',prNum:8000,cat:'Iluminación',sub:'LED',img:null,activo:true,popular:true},
   ],
   svcs:[{n:'Revisión panel',p:'₡15.000'},{n:'Toma corriente',p:'₡12.000'},{n:'Breaker',p:'₡20.000'}]
  }
]
// Guardia contra elementos undefined (arrays con huecos)
.filter(Boolean);

export default PROVEEDORES;
